# Install Numpy

In [1]:
#!pip install numpy

# Load Library

In [2]:
import numpy as np

# Create Numpy

Numpy can be used to create n-dimensional array

In [4]:
randArr = np.random.rand(2,3)
randArr

array([[0.42178888, 0.40468902, 0.87316724],
       [0.27404174, 0.07040089, 0.27913641]])

In [5]:
data = np.random.rand(2,3,4)
zeros = np.zeros((2,2,2))
ones = np.ones((2,3,4))
full = np.full((2,3,4), 7)

In [6]:
data

array([[[0.49833573, 0.35814805, 0.45583988, 0.11619984],
        [0.95797533, 0.4859873 , 0.40855983, 0.76210238],
        [0.5210984 , 0.67240998, 0.34746058, 0.36727317]],

       [[0.65274093, 0.51170457, 0.01290777, 0.95206438],
        [0.6980537 , 0.98085035, 0.71615256, 0.45708538],
        [0.23405486, 0.66995325, 0.82233798, 0.54489554]]])

In [7]:
zeros

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [8]:
ones

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [9]:
full

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

In [14]:
full2 = np.full((5, 2), 7)
full2

array([[7, 7],
       [7, 7],
       [7, 7],
       [7, 7],
       [7, 7]])

# Create a custom array

In [15]:
arr = np.array([[1,2,3,4],[1,2,3,4], [4,5,6, 7]])
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [4, 5, 6, 7]])

In [16]:
type(arr)

numpy.ndarray

In [17]:
arr.shape

(3, 4)

# Read

In [18]:
data

array([[[0.49833573, 0.35814805, 0.45583988, 0.11619984],
        [0.95797533, 0.4859873 , 0.40855983, 0.76210238],
        [0.5210984 , 0.67240998, 0.34746058, 0.36727317]],

       [[0.65274093, 0.51170457, 0.01290777, 0.95206438],
        [0.6980537 , 0.98085035, 0.71615256, 0.45708538],
        [0.23405486, 0.66995325, 0.82233798, 0.54489554]]])

In [19]:
shape = data.shape
shape

(2, 3, 4)

In [20]:
size = data.size
size

24

In [21]:
types = data.dtype
types

dtype('float64')

# Slicing

In [22]:
data

array([[[0.49833573, 0.35814805, 0.45583988, 0.11619984],
        [0.95797533, 0.4859873 , 0.40855983, 0.76210238],
        [0.5210984 , 0.67240998, 0.34746058, 0.36727317]],

       [[0.65274093, 0.51170457, 0.01290777, 0.95206438],
        [0.6980537 , 0.98085035, 0.71615256, 0.45708538],
        [0.23405486, 0.66995325, 0.82233798, 0.54489554]]])

In [23]:
data[0]

array([[0.49833573, 0.35814805, 0.45583988, 0.11619984],
       [0.95797533, 0.4859873 , 0.40855983, 0.76210238],
       [0.5210984 , 0.67240998, 0.34746058, 0.36727317]])

In [24]:
data[0:2]

array([[[0.49833573, 0.35814805, 0.45583988, 0.11619984],
        [0.95797533, 0.4859873 , 0.40855983, 0.76210238],
        [0.5210984 , 0.67240998, 0.34746058, 0.36727317]],

       [[0.65274093, 0.51170457, 0.01290777, 0.95206438],
        [0.6980537 , 0.98085035, 0.71615256, 0.45708538],
        [0.23405486, 0.66995325, 0.82233798, 0.54489554]]])

In [25]:
data[-1]

array([[0.65274093, 0.51170457, 0.01290777, 0.95206438],
       [0.6980537 , 0.98085035, 0.71615256, 0.45708538],
       [0.23405486, 0.66995325, 0.82233798, 0.54489554]])

In [26]:
data

array([[[0.49833573, 0.35814805, 0.45583988, 0.11619984],
        [0.95797533, 0.4859873 , 0.40855983, 0.76210238],
        [0.5210984 , 0.67240998, 0.34746058, 0.36727317]],

       [[0.65274093, 0.51170457, 0.01290777, 0.95206438],
        [0.6980537 , 0.98085035, 0.71615256, 0.45708538],
        [0.23405486, 0.66995325, 0.82233798, 0.54489554]]])

In [27]:
data[0][0][0]

0.49833573178314794

In [28]:
data[0][0:2]

array([[0.49833573, 0.35814805, 0.45583988, 0.11619984],
       [0.95797533, 0.4859873 , 0.40855983, 0.76210238]])

In [29]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [30]:
list1

array([0.28867657, 0.49936922, 0.24538865, 0.28510851, 0.95921054,
       0.28653244, 0.5741769 , 0.15600395, 0.36299096, 0.88580105])

In [31]:
list2

array([0.03521954, 0.93878183, 0.47703129, 0.61021787, 0.96137491,
       0.17028628, 0.14424841, 0.5791241 , 0.27462383, 0.93793825])

In [32]:
# Basic Math
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mul = np.multiply(list1, list2)
dot = np.dot(list1, list2)

In [33]:
add

array([0.3238961 , 1.43815105, 0.72241994, 0.89532638, 1.92058544,
       0.45681872, 0.71842532, 0.73512806, 0.63761479, 1.82373929])

In [34]:
sub

array([ 0.25345703, -0.43941261, -0.23164264, -0.32510935, -0.00216437,
        0.11624616,  0.42992849, -0.42312015,  0.08836713, -0.0521372 ])

In [35]:
div

array([8.19648973, 0.5319332 , 0.51440788, 0.46722413, 0.99774867,
       1.68265134, 3.98047293, 0.26937914, 1.32177515, 0.94441297])

In [36]:
mul

array([0.01016705, 0.46879875, 0.11705807, 0.17397831, 0.92216094,
       0.04879254, 0.08282411, 0.09034565, 0.09968597, 0.83082668])

In [37]:
dot

2.844638065958893

In [ ]:
#Statistical Functions SAPLEMM
sqrt = np.sqrt(25)
ab = np.abs(-5)
power = np.power(3, 2)
log = np.log(100)
ex = np.exp([3,5])
minim = np.min(list1)
maxm = np.max(list2)

In [ ]:
maxm

In [ ]:
data

In [ ]:
data[0][0][0] = 700
data

In [ ]:
data.sort()

In [ ]:
data

In [38]:
data

array([[[0.49833573, 0.35814805, 0.45583988, 0.11619984],
        [0.95797533, 0.4859873 , 0.40855983, 0.76210238],
        [0.5210984 , 0.67240998, 0.34746058, 0.36727317]],

       [[0.65274093, 0.51170457, 0.01290777, 0.95206438],
        [0.6980537 , 0.98085035, 0.71615256, 0.45708538],
        [0.23405486, 0.66995325, 0.82233798, 0.54489554]]])

In [39]:
data.shape

(2, 3, 4)

In [40]:
data = data.reshape(2,2, -1)
data

array([[[0.49833573, 0.35814805, 0.45583988, 0.11619984, 0.95797533,
         0.4859873 ],
        [0.40855983, 0.76210238, 0.5210984 , 0.67240998, 0.34746058,
         0.36727317]],

       [[0.65274093, 0.51170457, 0.01290777, 0.95206438, 0.6980537 ,
         0.98085035],
        [0.71615256, 0.45708538, 0.23405486, 0.66995325, 0.82233798,
         0.54489554]]])

In [41]:
data.shape

(2, 2, 6)

In [42]:
data

array([[[0.49833573, 0.35814805, 0.45583988, 0.11619984, 0.95797533,
         0.4859873 ],
        [0.40855983, 0.76210238, 0.5210984 , 0.67240998, 0.34746058,
         0.36727317]],

       [[0.65274093, 0.51170457, 0.01290777, 0.95206438, 0.6980537 ,
         0.98085035],
        [0.71615256, 0.45708538, 0.23405486, 0.66995325, 0.82233798,
         0.54489554]]])

In [43]:
data.shape

(2, 2, 6)

In [45]:
data = data.reshape(24)

In [46]:
data

array([0.49833573, 0.35814805, 0.45583988, 0.11619984, 0.95797533,
       0.4859873 , 0.40855983, 0.76210238, 0.5210984 , 0.67240998,
       0.34746058, 0.36727317, 0.65274093, 0.51170457, 0.01290777,
       0.95206438, 0.6980537 , 0.98085035, 0.71615256, 0.45708538,
       0.23405486, 0.66995325, 0.82233798, 0.54489554])

In [47]:
data = data.reshape(3, 2, -1)
data

array([[[0.49833573, 0.35814805, 0.45583988, 0.11619984],
        [0.95797533, 0.4859873 , 0.40855983, 0.76210238]],

       [[0.5210984 , 0.67240998, 0.34746058, 0.36727317],
        [0.65274093, 0.51170457, 0.01290777, 0.95206438]],

       [[0.6980537 , 0.98085035, 0.71615256, 0.45708538],
        [0.23405486, 0.66995325, 0.82233798, 0.54489554]]])

In [ ]:
scores = np.zeros(8)
scores

In [ ]:
scores = np.append(scores, [3,4])
scores

In [ ]:
scores.size

In [ ]:
#insert 1 at location 2
scores = np.insert(scores, 2, 1)
scores

# Delete

In [ ]:
data

In [ ]:
np.delete(data, 0, axis = 1 )

# Reshape

In [ ]:
data

In [ ]:
data.shape

In [ ]:
data2 = data.reshape(24)

In [ ]:
data2

In [ ]:
data2.shape

In [ ]:
data3 = data.reshape(4,6)

In [ ]:
data3

In [ ]:
data3.shape